[project]
name = "big-vision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chex>=0.1.86",
    "distrax>=0.1.5",
    "einops>=0.8.0",
    "flax>=0.9.0",
    "jax[cuda12]>=0.4.33",
    "numpy<2.0",
    "optax>=0.2.3",
    "orbax>=0.1.9",
    "overrides>=7.7.0",
    "protobuf>=5.28.2",
    "sentencepiece>=0.2.0",
    "tensorflow-cpu>=2.9.0",
    "tensorflow-datasets>=4.9.6",
    "tensorflow-text>=2.9.0",
]
